# This is the dockerfile to build a dev environment, include the tools you want in here that would normally not be in a production build
FROM ubuntu:17.10

# Installing required packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update

# Install required packages
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
    perl \
    libhtml-treebuilder-xpath-perl \
    curl \
    python \
    less \
    ngrep \
    tcpdump \
    vim \
    emacs \
    python-mode \
    make \
    net-tools \
    mysql-server \
    mysql-client \
    mysql-common \
    libclass-dbi-mysql-perl \
    gcc

# Perl junk
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y cpanminus

RUN  cpan install HTML::TableContent
RUN  cpan install HTML::TableExtract
RUN  cpan install PAR
RUN  cpan install PAR::Dist
RUN  cpan install JSON
RUN  cpanm install --installdeps pp

# Python modules

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install -y python-pip
RUN easy_install pip
RUN easy_install requests

# command line json parser, useful for pretty printing JSON output from curl, i.e. curl "http://blahblach" | jq
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y jq

WORKDIR /app



